# Mortality Prediction Simulation Configuration
data_dir: ${oc.env:TOKENIZED_TRAIN_DIR}
output_dir: ${oc.env:MORTALITY_RESULTS_DIR}
num_patients: 50

target_death_patients: 25
num_trajectories_per_patient: 20 # Run 20 trajectories per patient

max_tokens: 500  # Safety limit - trajectories stop at death/discharge
temperature: 1.0
base_seed: 42

# Command line flags:
# --patient-cache <path> 
# --discard-unfinished-trajectories   

models:
  "Monolith":
    # path: "/home/sud/temp_/ehr_stuff/EHR_FM/outputs/2026-01-05/19-00-23_model=gpt2_small_monolith,train=monolith_million,world_size=auto/best_model.pt"
    path: ${oc.env:BEST_MODEL_PATH}
  # "2-Expert":
  #   path: "/home/sud/temp_/ehr_stuff/EHR_FM/outputs/2025-12-05/16-12-39_model=gpt2_small_2exp,train=2_exp,world_size=auto/best_model.pt"
